### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by tilt-me** [hugabor/bundle-js#2]
I'm using bundle-js on my linux box, and I get this error when launch `bundle-js` in my working directory:
> /usr/bin/env: ‘node\r’: No such file or directory

It seems like a matter of newlines: on Linux (and Mac, I suppose), Windows line endings throw the error I reported:
https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

If I modify the file `/node_modules/bundle-js/bin/bundle-js.js`, converting end of line to Unix/Os X, I get no error anymore on command line.

**Comment by hugabor** [comment]
@tilt-me 
Hey, I'm not 100% sure what you are talking about. I have not tested `bundle-js` on linux or mac (I developed it on windows at the time) that is true. I had hoped that line-endings wouldn't be an issue since I tried to standardize the way paths are being stored.

It seems you have found something I missed. Would you mind submitting a pull request that fixes this issue?
