### ISSUE TITLE
env: node\r: No such file or directory on OSX

### ISSUE THREAD

**Issue by gkiszczak** [hugabor/bundle-js#4]
Tried to use bundle-js on OSX 10.12.5 but only getting the:

> env: node\r: No such file or directory 

Node ver: 8.1.4
npm ver: 5.3.0
node installed via brew

**Comment by henrysearle** [comment]
Also had this issue and found a workaround. The script has \r at the end instead of \n - I just updated the script locally.

You can use this workaround, you may need to update the file location to where it's stored on your mac (this is the default location for global files)

`cat /usr/local/lib/node_modules/bundle-js/bin/bundle-js.js | tr -d '\r' > /usr/local/lib/node_modules/bundle-js/bin/bundle-js.js`

**Comment by hugabor** [comment]
Has this issue been fixed with f7b894b23fb24f42e6a618ae915de91cc9775bbe ?
